// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _elephant_profile_H_
#define _elephant_profile_H_

extern const unsigned int elephant_profile_width;
extern const unsigned int elephant_profile_height;
extern const int elephant_profile_size;
extern const unsigned short elephant_profile[];

#endif

