// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _elephant_H_
#define _elephant_H_

extern const unsigned int elephant_width;
extern const unsigned int elephant_height;
extern const int elephant_size;
extern const unsigned short elephant[];

#endif

